name: Deploy to Edgeserver

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: "🚚 Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-upload@master
        with:
          app_id: "157549662935453696"
          server: https://app.edgeserver.io
          token: ${{ secrets.EDGESERVER_TOKEN }}
          directory: web